class Table:
    __tablename__ = 'stock_price'
    code = 'code'
    symbol = 'code'
    date = 'date'
    open = 'open'
    high = 'high'
    low = 'low'
    close = 'close'
    volume = 'volume'
    trad_value = 'trad_value'
    fluc_rate = 'fluc_rate'
